# Generated by Django 4.1.7 on 2023-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('ville', models.TextField()),
                ('etat', models.TextField()),
                ('codePostal', models.TextField()),
            ],
        ),
    ]
