# Generated by Django 4.1.7 on 2023-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kordiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
