# Generated by Django 4.1.7 on 2023-04-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kordiApp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.TextField()),
                ('adressesMail', models.TextField()),
                ('Other_link', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='InformationUser')),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kordiApp.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUsers', models.EmailField(max_length=254)),
                ('passwordUsers', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='informationuser',
            name='userLocalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kordiApp.localization'),
        ),
    ]
